name = "NetworkSolvers"
uuid = "31404548-2b48-4190-b5cd-dc6b4eddfaec"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.0"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
NDTensors = "23ae76d9-e61a-49c4-8f12-3f1a16adf9cf"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Graphs = "1.12.0"
ITensorNetworks = "0.13.1"
ITensors = "0.8.0"
IterTools = "1.10.0"
KrylovKit = "0.6, 0.7, 0.8"
NamedGraphs = "0.6.4"
julia = "1.10"
