name = "NetworkSolvers"
uuid = "31404548-2b48-4190-b5cd-dc6b4eddfaec"
authors = ["ITensor developers <support@itensor.org> and contributors"]
version = "0.1.1"

[deps]
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
ITensorNetworks = "2919e153-833c-4bdc-8836-1ea460a35fc7"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
NDTensors = "23ae76d9-e61a-49c4-8f12-3f1a16adf9cf"
NamedGraphs = "678767b0-92e7-4007-89e4-4527a8725b19"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
TensorOperations = "6aa20fa7-93e2-5fca-9bc0-fbd0db3c71a2"

[compat]
Graphs = "1.12.0"
ITensorNetworks = "0.11, 0.12, 0.13"
ITensors = "0.7, 0.8, 0.9"
IterTools = "1.10.0"
KrylovKit = "0.6, 0.7, 0.8, 0.9"
NamedGraphs = "0.6.8"
julia = "1.10"
